apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    run: udagram-reverseproxy
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: udagram-reverseproxy