apiVersion: v1
kind: Service
metadata:
  name: udagram-api-auth
  labels:
    run: udagram-api-auth
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: udagram-api-auth