version: "3"
services:
 reverseproxy:
   build: ../reverseproxy/.
   ports:
     - 8080:8080
   restart: always
   depends_on:
    - udagram-api-feed
    - udagram-api-auth  
 udagram-api-feed:
  build: ../udagram-api-feed/.
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   POSTGRES_USERNAME: $POSTGRES_USERNAME
   POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
   POSTGRES_DB: $POSTGRES_DB 
   POSTGRES_HOST: $POSTGRES_HOST 
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://localhost:8100"
 udagram-api-auth:
  build: ../udagram-api-auth/.
  environment:
   POSTGRES_USERNAME: $POSTGRES_USERNAME
   POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
   POSTGRES_DB: $POSTGRES_DB 
   POSTGRES_HOST: $POSTGRES_HOST 
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://localhost:8100"
 udagram-frontend:
  build: ../udagram-frontend/.
  ports:
   - "8100:80"